### ISSUE TITLE
tmux three_drones_gps not taking off

### ISSUE THREAD

**Issue by bconvens** [ctu-mrs/simulation#11]
When I launch the default tmux script three_drones_gps the drones don't take off in simulation.
Only once I saw a single drone taking off, but the other remained on the ground unarmed . 
The tmux example with many drones is even more a problem.
For 2 drones taking off seems to work in most cases. Although sometimes I have to relaunch before it works for 2 drones.
Is non-deterministic behavior normal? 
How can I easily simulate for multiple drones the non-vision examples (e.g. 10 drones?). 
My PC specs (although I think the problem is somewhere else):
![image](https://user-images.githubusercontent.com/12151591/84560138-44fafb80-ad41-11ea-87e0-c61e6dcda5d4.png)
Thanks!

**Comment by klaxalk** [comment]
Hey, the problem is possible on my side. The takeoff sequence in most of the sessions is missing some "sleeps", which might not matter unless the computer is struggling. I updated the sequence in the scripts from:
```bash
        - 'export UAV_NAME=uav1;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
```
to
```bash
        - 'export UAV_NAME=uav1;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          sleep 2;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
```
and tested all of the example sessions, so they work now for me. So please pull the latest commit in the `simulation` package. If the problem persists, please, let me know. The next step would be to analyze the output on the "automatic_start" tab, or the "control" tab, which will tell you why the takeoff was not possible. However, it is likely that you might not be able to simulate 10 UAVs with your laptop. The simulation is rather demanding. For 10 UAVs, I would recommend simulation on a desktop machine with at least something like i7-7700. If you manage to fly with 3 UAVs, please check the "realtime factor" in the Gazebo window. If it's below 0.8, I would hesitate to simulate more drones in realtime. An alternative option might be to slow down the simulation, as shown [here](https://ctu-mrs.github.io/docs/simulation/simulation_speed.html) (it is better to set the realtime factor manually to a value, which is below your maximum achievable one when not limiting it).

For context, here is a screenshot of how the realtime factor and the CPU load looks on my i7-8700 with 10 UAVs:
![Selection_098](https://user-images.githubusercontent.com/1611176/84572815-e499a780-ad9c-11ea-86f0-8814adb959a7.png)

**Comment by bconvens** [comment]
I pulled the commits in which you added sleeps. This does not directly seem to improve the three_drone_gps example. I launched this script about 10 times: most often 1 drone takes of or no drones take off. Only once all 3 drones took off and I successfully could send set-points. After giving the goto commands, the average real-time factor dropped from 0.7 to 0.3.
![Screenshot from 2020-06-16 11-44-27](https://user-images.githubusercontent.com/12151591/84760215-fd39d580-afc7-11ea-99b4-4e6b257054fc.png)

After that I tried to reduce the real-time factor to 0.5 and to 0.1. Now only 2 out of 3 drones spawn (which is worse than using a factor of 1.0) and I get this error:
![Screenshot from 2020-06-16 10-53-50](https://user-images.githubusercontent.com/12151591/84758208-7126ae80-afc5-11ea-9996-73c11a775f0e.png)
Thanks for the help!

**Comment by klaxalk** [comment]
Hey, ye, to me, it looks like your computer is struggling a lot with the Gazebo simulator. It's possible that when the realtime-ness is bad, that something desynchronizes in the PX4 SITL (which lives in its world), and then it crashes. I don't know how I could help. One option might be to spawn the UAVs in a sequence. There may be a race condition within a simulator itself, which does not occur on more powerful machines. So try to add some sleeps to spawn the vehicles, maybe with 15 s delay between each other.

I don't know why your laptop would do that. It seems to be a decent machine. But in the end, the CPU is what matters the most in here, and yours is pretty old, plus it is laptop CPU. But on paper, it should be enough, though.

What is your realtime factor with the _one_drone_gps_ example?

Also, are you building our stuff within our default "mrs_workspace"? We use a preset "reldeb" profile by default, which uses compilation optimizations. If you use your workspace by any chance, make sure your stuff is built with -O3.

**Comment by bconvens** [comment]
Hey!
I took a step back and tested the _one_drone_gps_ example 4 times. The drone always takes off and I can always command the drone with goto commands. It seems to work when no real-time factor is set in the bashrc and also if it is set to 1.0. I don't know when the real-time factor is "good enough". I recorded my screen and the real-time factor is not changing a lot and close to 1.0 in 3 out of 4 tests. I see most often values between 0.88-1.0. For 1 out of the 4 tests it was significantly lower in average about 0.80, between 0.72 and 0.90. Is this normal that it can drop in average about 10-15% for the same test?
My cpu% is changing more significantly during the goto tests, between about 45% and 90%. Is this normal and good enough?

What I don't understand is that when I set the real-time factor to a lower value than 1.0, gazebo always drops to an even lower real-time factor (the value in brackets): e.g. 0.9 (0.71), 0.75 (0.60), 0.5 (0.31), 0.3 (0.27) or even as low as 0.2 (0.17). Also for a real-time factor of 0.2, the cpu% varies between 35% and 90%. So what's the advantage of setting a lower real-time factor in the bashrc?
The behavior for a real-time factor of 1.6 is also strange. For some periods it is for 10s around 1.3-1.4 surprisingly, then it drops to 0.6 while the drone is just hovering and remains there... Is this normal?

When comparing my processor with yours [here](https://cpu.userbenchmark.com/Compare/Intel-Core-i7-8700K-vs-Intel-Core-i7-4910MQ/3937vsm9700), your comes out better, but with only a 37% faster effective speed. 
To which value did you preset your real-time factor and in which range does it vary for your test with 10 drones (is it always 0.9 as in your screenshot)?

Is there a way to reduce the required CPU of the MRS software? Which modules could be easily change parameters such that they require less computational power? I assume the MPC tracker is consuming a lot of CPU? How to reduce it? Where could I reduce the prediction horizon?
Which tracker / control / other settings would you advice to change to reduce cpu usage?

For compiling I just followed the steps on your wiki. I run the example in the mrs_workspace, so that's the workspace I compiled. How should I compile code in the workspace folder (where I will put my code later) and compile it with -O3? what should I understand from the "reldep" profile?

Thanks again for the help!!!

**Comment by klaxalk** [comment]
Hey, sorry for getting back late. The variability in your results is strange, and it does not happen to me, even not on my laptop. I get the realtime factor when I set it in the .bashrc. The comparison of the CPUs does not really give them justice. I found that synthetic benchmarks do not really reflect the performance of a CPU in *realtime* performance, such as the simulation / ROS control pipeline. I guess its mainly because the ROS system is not much predictable, it contains many threads with really variable execution times, etc. A CPU is much more than just clock X instructions = power, stuff like instruction scheduling, speculative execution, caching have a big play in it. I am not even mentioning that my PC has DDR4, which might help a lot with this kind of application. Long story short, upgrading to a newer generation often gives more like double the performance in the simulation than the 15% that benchmarks tell you. Not to mention how vast is the difference between desktop and laptop systems. Not only the CPU but the RAM speeds, cache sizes, bus speeds, etc. We have seen this a lot within the last five years. So I still think it could be your CPU.

We usually compile our stuff with -O2, see the build profiles we create within the catkin workspace. Our default profile is the *reldeb* profile, You can update the profile to *release* (```catkin profile set release```), which has -O3, it might help. Maybe, update the whole uav_core if you can, I am now pre-building the MPC solvers with -O3 and putting them there as binaries. The build takes 5 minutes on i9, so it should be worth it.

There are some options to make the pipeline run faster. Shortening the MPC Tracker's horizon is not an option.
It is "baked" in the solver. However, you can lower the maximum number of iterations in its config file, which will directly lower the computational time. You can also make the whole estimation & control pipeline run on a lower rate, in ```default.yaml``` in **mrs_uav_odometry**, change the
```yaml
publish_rate:
  main: 100 # [Hz] main and aux odometry
```
to, e.g., 25 Hz, which will slow everything down (the control pipeline's rate is tight to the estimator rate). I guess since you probably aim for swarming, this should not influence you much in the control performance.
You could even go lower than 25.

I just tested a flight with 25 Hz (odometry main rate) and a maximum of 5 iterations on each axis of the MPC Tracker, and it "flies". I would trust it for a fast or aggressive flight, but it might work for you.
