### ISSUE TITLE
Disable Arming and SafetyArea

### ISSUE THREAD

**Issue by dringakn** [ctu-mrs/simulation#14]
Hi,

How can I disable the arming requirement of the uav in the simulation?
Furthermore how can I disable (or increase the limits) the safety area bounding box for the drone in the gazebo simulation?
The uav automatically lands and disarm itself upon touching the bounding box. Re-executing the commands sequence (arming, set_mode) within the takeoff tab of the tmux session doesn't make it hover again, until the whole simulation is restarted!
 
Regards,

**Comment by klaxalk** [comment]
Hey, arming is not explicitly limited by our platform. We actually do not allow arming using our software since it is a safety hazard. On a real UAV, the arming is done manually using an RC transmitter, but in the simulation, we call service directly to MAVROS, which should be done carefully. However, we have a prerequisite for enabling the output of our control pipeline, aka. "setting motors on". Most of them can't be disabled but some of them can. If you have a problem with some part of takeoff, please be more specific. The ones which can are:
- The UAV must be within a virtual safety area defined within the "[world](https://github.com/ctu-mrs/mrs_uav_general/tree/master/config/worlds)" file. To disable it, you have to disable the whole safety area with its appropriate config file.
- The virtual bumper must tell safe results. To disable it, disable the bumper in [control_manager.yaml](https://github.com/ctu-mrs/mrs_uav_managers/blob/master/config/default/control_manager.yaml).

The safety area can be changed or disabled within its config file in [here](https://github.com/ctu-mrs/mrs_uav_general/tree/master/config/worlds). The name of the config is deduced from an environment variable WOLRD_NAME (either in .bashrc or directly within the tmux session), e.g., WORLD_NAME=simulation becomes world_simulation.yaml. You can also load a particular world file directly by defining WORLD_FILE=./my_world_file.yaml.

Regarding the landing: within the simulation, we do not disarm the vehicles upon landing, however, we do on real hardware. This can be easily configured via [uav_manager.yaml](https://github.com/ctu-mrs/mrs_uav_managers/blob/master/config/default/uav_manager.yaml) with the `landing/disarm` parameter. When landed in simulation, you can take off on demand by just calling the `uav_manager/takeoff service`.
