### ISSUE TITLE
wrong frame rate when making videos with the "static_camera" in gazebo

### ISSUE THREAD

**Issue by linuxdronethesis** [ctu-mrs/simulation#15]
Hello,

I am launching a simulation using the tmux script "one_drone_gps". I am then inserting a "static_camera" in gazebo and recording compressed images in a bag file as explained in https://ctu-mrs.github.io/docs/simulation/gazebo_video.html. Then I am extracting pictures successfully with the launch file present in the previous link. However the number of images does not correspond to the frame rate in /git/simulation/ros_packages/mrs_gazebo_common_resources/models/static_camera (30). No matter the selected frame rate there is a random number of images between 4 and 1 per second, so really low. The obtained video is thus really bad. Would it be possible to help me ? 

Thank you in advance

**Comment by spurnvoj** [comment]
Hi, What is the load and CPU usage of your PC during simulating? I think that the PC doesn’t have enough computation power to render pictures on such frequency. I suggest slowing down the simulation (see [link](https://ctu-mrs.github.io/docs/simulation/simulation_speed.html)) and lower the resolution of the camera. Mostly 720p is enough for nice videos 🙂 For that, change the same file as for camera rate `~/git/simulation/ros_packages/mrs_gazebo_common_resources/models/static_camera/model.sdf`

Also, are you recording only the topic from this camera? Because another issue can be with your hard drive that it cannot save so much data per second on the disk. Check the bandwidth of the message by calling `rostopic bw topic_of_camera`

**Comment by linuxdronethesis** [comment]
Thank you for your detailed answer
